name: Pre-release SDK


on:
  pull_request
    # workflow_dispatch:
    #     inputs:
    #         dryRun:
    #             description: 'Do a dry run to preview instead of a real release [true/false]'
    #             required: true
    #             default: 'true'
    #         release-order:
    #             description: 'Which Phase are you releaseing? [release-order-a/release-order-b/release-order-c]'
    #             required: true

jobs:

  # TODO: Steps
        # 1. Check if input string for release order branch
        # 2. Check if input string for release/tag branch exists

    # TODO: Maybe Refactor into reusable job
    verify-release-order-branch:
      name: Verify Release Order Branch
      runs-on: ubuntu-latest
      steps:
        # TODO: Replace with input string
        - name: Checkout Release Order (<branch name>)
          uses: actions/checkout@v3
          with:
            # TODO: Replace with input
            ref: release-order-a

    verify-sdk-version-branch:
      name: Verify SDK Version
      runs-on: ubuntu-latest
      steps:
        # TODO: Replace with input string
        - name: Checkout SKD Version (<version number>)
          uses: actions/checkout@v3
          with:
            # TODO: Replace with input
            ref: release/2.23.4

    push-pre-release-branch:
      # TODO: Replace with branch name
      name: Deploy Pre-Release to (<branch name>)
      needs:
        - verify-release-order-branch
        - verify-sdk-version-branch
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
        GIT_AUTHOR_NAME: mparticle-automation
        GIT_AUTHOR_EMAIL: developers@mparticle.com
        GIT_COMMITTER_NAME: mparticle-automation
        GIT_COMMITTER_EMAIL: developers@mparticle.com

      steps:
        # TODO: Replace with input string
        - name: Checkout SKD Version (<version number>)
          uses: actions/checkout@v3
          with:
            # TODO: Replace with input
            ref: release/2.23.4
        
        - name: Force Push Pre-Release Branch
          # TODO: Add when dryRun is enabled
          # if: ${{ github.event.inputs.dryRun == 'false' }}
          run: |
                git push origin HEAD:release-order-a -f