name: Release to CDN and Synchronize Branches

on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: 'Do a dry run to preview instead of a real release [true/false]'
                required: true
                type: boolean
                default: true
            versionNumber:
                description: 'Which SDK version to syncronize? [X.XX.XX]'
                required: true
                type: string

jobs:
    verify-version-number:
      name:  Verify SDK Version (${{ github.event.inputs.versionNumber}})
      runs-on: ubuntu-latest
      steps:
        # As a safe guard, if a valid release branch does not exist,
        # this step will fail and throw an error
        - name: Checkout SDK Version (${{ github.event.inputs.versionNumber}})
          uses: actions/checkout@v3
          with:
            ref: release/${{ github.event.inputs.versionNumber}}


    synchronize-sdk:
      name: Synchronize SDK to all branches
      runs-on: ubuntu-latest
      needs:
        - verify-version-number
      env:
        GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
        GIT_AUTHOR_NAME: mparticle-automation
        GIT_AUTHOR_EMAIL: developers@mparticle.com
        GIT_COMMITTER_NAME: mparticle-automation
        GIT_COMMITTER_EMAIL: developers@mparticle.com

      steps:
        - name: Checkout master branch
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            repository: ${{ github.repository }}
            token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
            ref: master

        - name: Merge release branch into master branch
          if: ${{ github.event.inputs.dryRun == 'false' }}
          run: |
            git pull origin release/${{ github.event.inputs.versionNumber}}
        
        # We will eventually replace master with main
        - name: Push release commits to main and master
          if: ${{ github.event.inputs.dryRun == 'false' }}
          run: |
                git push origin HEAD:master
                git push origin HEAD:main

        - name: Push release commits to development
          if: ${{ github.event.inputs.dryRun == 'false' }}
          run: |
            git push origin HEAD:development

        - name: Push release commits to chore/dependabot
          if: ${{ github.event.inputs.dryRun }}
          run: |
            git push origin HEAD:chore/dependabot

        - name: Force Push release commits to Release Order Branches
          if: ${{ github.event.inputs.dryRun }}
          run: |
            git push origin HEAD:release-order-a -f
            git push origin HEAD:release-order-b -f
            git push origin HEAD:release-order-b -f